# default structrue, just a set-up!
version: "3"
services:
  kiama-network:
    image: # kiama network image id from cloud repo
    ports:
      - 8081: 8081
  mongodb:
    image: mongo
    ports:
      - 27017: 27017
    volumes:
      - mongo-database: /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - 5555: 5555
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  redis:
    image: redis
    ports:
      -6379: 6379
volumes:
  mongo-database:
    driver: local
# for building the cloud directly and it's optional
# steps:
# - name: node
# entrypoint: npm
# args: ["install"]
#- name: node
#  entrypoint: npm
#  args: ['test']
# - name: node
# entrypoint: npm
# args: ["run", "build"]
